language: go
sudo: required

dist: trusty
group: deprecated-2017Q4

git:
  depth: 3
  submodules: false

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - (git diff master --name-status | grep "^D" -v | sed "s/^.\t//g" | grep "\.go$$" | bash scripts/cscheck.sh) || exit 1

notifications:
  email: false
