fixers:
   no_new_line_before_error_check:
       recommend: true
       lint: true
       fix: true

   use_path_join:
       recommend: true
       lint: true
       fix: true

questionable:
    - use_path_join
