fixers:
   no_new_line_before_error_check:
       recommend: true
       lint: true
       fix: true
   file_header:
       recommend: true
       lint: true
       fix: true
       options:
            header: |
                // This header required line 1
                // This header required line 2

            lintText: License header required

   use_path_join:
       recommend: true
       lint: true
       fix: true

   group_import:
       recommend: true
       lint: true
       fix: true
       options:
            stdLib: true
            lintText: Group stdLib imports

   alternative_call:
       recommend: true
       lint: true
       fix: true
       options:
            selector: logp.Warn
            alternative: logp.Err
