fixers:
   no_new_line_before_error_check:
       recommend: true
       lint: true
       fix: true
   file_header:
       recommend: true
       lint: true
       fix: true
       options:
            header: |
                // This header required line 1
                // This header required line 2

            lintText: License header required

   use_path_join:
       recommend: true
       lint: true
       fix: true

questionable:
    - use_path_join
