fixers:
   no_new_line_before_error_check:
       type: no_new_line_before_error_check
       recommend: true
       lint: true
       fix: true

   license_header:
       type: file_header
       recommend: true
       lint: true
       fix: true
       options:
            header: |
                // This header required line 1
                // This header required line 2

            lintText: License header required

   use_path_join:
       type: use_path_join
       recommend: true
       lint: true
       fix: true

   group_std_imports:
       type: group_import
       recommend: true
       lint: true
       fix: true
       options:
            stdLib: true
            lintText: Group stdLib imports

   log_err_instead_log_warn:
       type: alternative_call
       recommend: true
       lint: true
       fix: true
       options:
            selector: logp.Warn
            alternative: logp.Err
